### ISSUE TITLE
显示已损坏  打不开

### ISSUE THREAD

**Issue by 2606090723** [Jeric-X/SyncClipboard.Desktop#1]
![image](https://github.com/Jeric-X/SyncClipboard.Desktop/assets/24692385/07524ca7-791d-45fb-b0a5-b664aa783a7c)

**Comment by Jeric-X** [comment]
在终端中执行`sudo xattr -d com.apple.quarantine /Applications/SyncClipboard.app`

**Comment by 2606090723** [comment]
哇哦 可以运行了

**Comment by Ahjol-ba** [comment]
> `sudo xattr -d com.apple.quarantine /Applications/SyncClipboard.app`

很奇怪，我是MacBook air m1， 下载arm64版本显示损坏，下载x64能正常运行，是不是标反了？😂

**Comment by Jeric-X** [comment]
arm的mac能转译运行x64程序
